### PR TITLE
:lady_beetle: Fix the hang of the spinner and progress bar on stop

### LINKED ISSUE #160: Spinner can hang forever while stopping, when executed on fast rendering setups
On some fast rendering setups like:

* unit tests,
* background processes,
* pipe'ing output/input

the spinner could hang indefinitely on `Quit()`, and `Wait()` method:

https://github.com/knative/client-pkg/blob/325b48ca6ffc86103396ccac507da1e6c04301aa/pkg/output/tui/spinner.go#L93-L94

See the goroutines dump: https://gist.github.com/cardil/039c0691d94b9537126b50361bbf9d3e

/kind bug

### LINKED ISSUE #161: ProgressBar can hang forever while stopping, when executed on fast rendering setups
On some fast rendering setups like:

* unit tests,
* background processes,
* pipe'ing output/input

the spinner could hang indefinitely on `Wait()`, and `<-b.ended` method:

https://github.com/knative/client-pkg/blob/325b48ca6ffc86103396ccac507da1e6c04301aa/pkg/output/tui/progress.go#L255-L257

See the goroutines dump: https://gist.github.com/cardil/7fa34571b0dc0770113b5ff707f84841

/kind bug

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :lady_beetle: Fix the hang of the spinner on stop
- :lady_beetle: Fix the hang of the progress bar on stop

/kind bug

Fixes #160
Fixes #161

**Release Note**

```release-note
The spinner and progress bar will no longer hang on exit, which may occur on some fast rendering setups
```

### CODE REVIEW

**Comment by cardil** [comment]
With https://github.com/knative/client-pkg/pull/162/commits/0ff3298a553c4fec8c69acfa8ee62a1ed08841e9 the hanging of #161 is fixed, but this causes the https://github.com/cardil/ghet to show bad UI - the progress bar stops rendering to early and the output could show progress bars which are not 100%, even if completed successfully:

```
$ go run ./cmd/ght download --destination /tmp/ghet golangci/golangci-lint
⛳️ Getting information about latest release Done
🎉 Found 2 matching assets for v1.57.1
📥 12 golangci-lint-1.57.1-linux-amd64.tar.gz  ████████████████████████████████████████████░░░░░░  88% ⋮  20.19 MiB/s ⋮  10.55 MiB
📥 22 golangci-lint-1.57.1-checksums.txt       ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░   0% ⋮   0.00 B/s   ⋮   5.13 KiB
🔍 Verifying checksum for golangci-lint-1.57.1-linux-amd64.tar.gz Done
✅ All checksums match the downloaded assets
📦 Extracting archive: golangci-lint-1.57.1-linux-amd64.tar.gz
🎯 golangci-lint  ████████████████████████████████████████████████████████████████████████████░░░  97% ⋮  58.18 MiB/s ⋮  26.64 MiB

```

**Comment by cardil** [comment]
/cc @dsimansk

I think I got it. This version was tested against both e2e tests in magetasks, and the ghet tool (the progress bar UI is completed now).

File: pkg/output/tui/progress.go [hunk 1]
```diff
@@ -175,17 +175,23 @@ func (b bubbleProgressHandler) speedChange() (tea.Model, tea.Cmd) {
...
 	}
 
 	return b, tea.Batch(cmds...)
 }
 
+func (b *BubbleProgress) quitSignal() tea.Cmd {
+	// The final pause is to give the progress bar a chance to finish its
+	// animation before quitting. Otherwise, it ends abruptly, and the user
+	// might not see the progress bar at 100%.
+	return tea.Sequence(b.finalPause(), tea.Quit)
```
Comment (cardil) [inline pkg/output/tui/progress.go:192]: I still don't like the additional wait. If your UI has a lot of progress bars, this wait will be visible.

But I don't see a way, with the current API of bubbles' progress, to achieve it otherwise...

Comment (cardil) [reply pkg/output/tui/progress.go:192]: I was experimenting with [ViewAs() func](https://pkg.go.dev/github.com/charmbracelet/bubbles/progress#Model.ViewAs). You could see the experiment here: https://github.com/cardil/knative-client-pkg/commit/5d19f314622770ea5f8bffdf4c509b3d14eddc3c

It worked. However, the output isn't what I was going for. The progress bar is always doubled. See:

```
$ go run ./cmd/ght download --destination /tmp/ghet golangci/golangci-lint
⛳️ Getting information about latest release Done
🎉 Found 2 matching assets for v1.57.1
📥 12 golangci-lint-1.57.1-linux-amd64.tar.gz  █████████████████████████░░  94% ⋮  20.09 MiB/s ⋮  10.55 MiB
📥 12 golangci-lint-1.57.1-linux-amd64.tar.gz  ███████████████████████████ 100% ⋮  20.09 MiB/s ⋮  10.55 MiB
📥 22 golangci-lint-1.57.1-checksums.txt       ░░░░░░░░░░░░░░░░░░░░░░░░░░░   0% ⋮   0.00 B/s   ⋮   5.13 KiB
📥 22 golangci-lint-1.57.1-checksums.txt       ███████████████████████████ 100% ⋮   0.00 B/s   ⋮   5.13 KiB
🔍🔍 Verifying checksum for golangci-lint-1.57.1-linux-amd64.tar.gz Done
✅ All checksums match the downloaded assets
📦 Extracting archive: golangci-lint-1.57.1-linux-amd64.tar.gz
🎯 golangci-lint  ██████████████████████████████████████████████████████░░  96% ⋮ 123.39 MiB/s ⋮  26.64 MiB
🎯 golangci-lint  ████████████████████████████████████████████████████████ 100% ⋮ 123.39 MiB/s ⋮  26.64 MiB
```
I think, there's no easy way to avoid the doubling this way. This is because, we print the line outside the control of the bubbletea renderer (which uses a special shell display mode).

Comment (dsimansk) [reply pkg/output/tui/progress.go:192]: I think, there's no easy way to avoid the doubling this way. This is because, we print the line outside the control of the bubbletea renderer (which uses a special shell display mode).

Comment (cardil) [reply pkg/output/tui/progress.go:192]: This is very similar to showing 100% of completeness. You just print `""` instead of the progress.

I don't think it is possible with the current API. When the `tea.Quit` command is handled, the rendered stops, and restores the terminal to standard output mode. So, you can't replace the line that was already written.

I think the bubbletea should allow defining the last `tea.Quit` state, that will be printed just before the exit, and without waiting for the animation loop to draw it.

**Review by dsimansk — APPROVED** [review]
/approve
/lgtm

I'm OK to merge per Chris' proposal even with not so polished end of progress bar for now. And further improve in next iterations. 

Adding hold for other reviews, feel free to unhold per my comment above.
/hold

**Comment by cardil** [comment]
/unhold

I'll create an issue to track the removal of the explicit wait. Thx @dsimansk!

File: pkg/output/tui/progress.go (hunk 1 above)
Comment (cardil) [reply pkg/output/tui/progress.go:192]: Tracked here: https://github.com/knative/client-pkg/issues/163

**Comment by lkingland** [comment]
/lgtm
/approve

Glad this is being merged now, and we can track that quirk separately 👍🏻
